/**
 * ROAS Service
 *
 * Service for ROAS (Return on Ad Spend) analytics with product and platform breakdown
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query'
import { rOASGetStats } from '~/api/generated/endpoints/roas/roas'
import type {
  ROASStatsDto,
  GetROASStatsRequest,
  ProductROASDto,
  PlatformROASDto,
} from '~/api/generated/models'

export interface ROASParams {
  startDate: string
  endDate: string
  productId?: string | null
  platform?: string | null
}

export interface ROASKpiData {
  totalAdSpend: number
  totalRevenue: number
  totalProfit: number
  overallROAS: number
  totalOrders: number
  averageCostPerOrder: number
}

export interface ProductROASData {
  productId: string
  productName: string
  totalAdSpend: number
  totalRevenue: number
  totalProfit: number
  roas: number
  ordersCount: number
  averageOrderValue: number
  costPerOrder: number
}

export interface PlatformROASData {
  platform: string
  totalAdSpend: number
  spendShare: number
  estimatedRevenue: number
  roas: number
  estimatedOrders: number
}

export type ROASLevel = 'excellent' | 'good' | 'average' | 'loss'

export function getROASLevel(roas: number): ROASLevel {
  if (roas >= 3.0) return 'excellent'
  if (roas >= 2.0) return 'good'
  if (roas >= 1.0) return 'average'
  return 'loss'
}

export function getROASColor(roas: number): string {
  const level = getROASLevel(roas)
  switch (level) {
    case 'excellent': return 'text-green-700 dark:text-green-400'
    case 'good': return 'text-green-500 dark:text-green-500'
    case 'average': return 'text-yellow-500 dark:text-yellow-400'
    case 'loss': return 'text-red-500 dark:text-red-400'
  }
}

export function getROASBgColor(roas: number): string {
  const level = getROASLevel(roas)
  switch (level) {
    case 'excellent': return 'bg-green-700'
    case 'good': return 'bg-green-500'
    case 'average': return 'bg-yellow-500'
    case 'loss': return 'bg-red-500'
  }
}

export function useROASService(params: Ref<ROASParams>) {
  const queryClient = useQueryClient()

  // Query key based on filters
  const queryKey = computed(() => [
    'roas',
    'stats',
    params.value.startDate,
    params.value.endDate,
    params.value.productId,
    params.value.platform,
  ] as const)

  // Use mutation for POST request (as generated by orval)
  const statsMutation = useMutation({
    mutationFn: (request: GetROASStatsRequest) => rOASGetStats(request),
  })

  // Auto-fetch when params change using a query wrapper
  const statsQuery = useQuery({
    queryKey,
    queryFn: () => rOASGetStats({
      startDate: params.value.startDate,
      endDate: params.value.endDate,
      productId: params.value.productId || null,
      platform: params.value.platform || null,
    }),
    staleTime: 30 * 1000, // 30 seconds
    gcTime: 5 * 60 * 1000, // 5 minutes
    refetchOnWindowFocus: true,
  })

  // Raw data
  const rawData = computed<ROASStatsDto | undefined>(() => statsQuery.data.value)

  // KPI Data
  const kpiData = computed<ROASKpiData>(() => {
    const data = rawData.value
    if (!data) {
      return {
        totalAdSpend: 0,
        totalRevenue: 0,
        totalProfit: 0,
        overallROAS: 0,
        totalOrders: 0,
        averageCostPerOrder: 0,
      }
    }

    return {
      totalAdSpend: data.totalAdSpend ?? 0,
      totalRevenue: data.totalRevenue ?? 0,
      totalProfit: data.totalProfit ?? 0,
      overallROAS: data.overallROAS ?? 0,
      totalOrders: data.totalOrders ?? 0,
      averageCostPerOrder: data.averageCostPerOrder ?? 0,
    }
  })

  // Product ROAS Data (for charts and tables)
  const productROASData = computed<ProductROASData[]>(() => {
    return (rawData.value?.byProduct ?? []).map((p: ProductROASDto) => ({
      productId: p.productId ?? '',
      productName: p.productName ?? '',
      totalAdSpend: p.totalAdSpend ?? 0,
      totalRevenue: p.totalRevenue ?? 0,
      totalProfit: p.totalProfit ?? 0,
      roas: p.roas ?? 0,
      ordersCount: p.ordersCount ?? 0,
      averageOrderValue: p.averageOrderValue ?? 0,
      costPerOrder: p.costPerOrder ?? 0,
    }))
  })

  // Platform ROAS Data (for charts and tables)
  const platformROASData = computed<PlatformROASData[]>(() => {
    return (rawData.value?.byPlatform ?? []).map((p: PlatformROASDto) => ({
      platform: p.platform ?? '',
      totalAdSpend: p.totalAdSpend ?? 0,
      spendShare: p.spendShare ?? 0,
      estimatedRevenue: p.estimatedRevenue ?? 0,
      roas: p.roas ?? 0,
      estimatedOrders: p.estimatedOrders ?? 0,
    }))
  })

  // Chart data for products (horizontal bar chart)
  const productChartData = computed(() => {
    const data = productROASData.value.slice(0, 10) // Top 10
    return {
      labels: data.map(p => p.productName),
      roas: data.map(p => p.roas),
      revenue: data.map(p => p.totalRevenue),
      adSpend: data.map(p => p.totalAdSpend),
    }
  })

  // Chart data for platforms (donut chart)
  const platformChartData = computed(() => {
    const data = platformROASData.value
    return {
      labels: data.map(p => p.platform),
      values: data.map(p => p.totalAdSpend),
      percentages: data.map(p => p.spendShare),
    }
  })

  // Loading state
  const isLoading = computed(() => statsQuery.isLoading.value)
  const isFetching = computed(() => statsQuery.isFetching.value)
  const error = computed(() => statsQuery.error.value)

  // Actions
  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['roas'] })
  }

  const refetch = () => statsQuery.refetch()

  return {
    // Raw data
    rawData,

    // Processed data
    kpiData,
    productROASData,
    platformROASData,
    productChartData,
    platformChartData,

    // State
    isLoading,
    isFetching,
    error,

    // Actions
    invalidate,
    refetch,
  }
}

// Re-export types
export type { ROASStatsDto, GetROASStatsRequest, ProductROASDto, PlatformROASDto }
